language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pycodestyle
# command to run tests
script:
  - pycodestyle --show-source --show-pep8 --ignore=E501,E241 .
